name: build docker image and publish to docker hub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: publish to docker hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pavled/jenkins-kernel-builder
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}